### ISSUE TITLE
Add async javascript support for open_email and friends

### ISSUE THREAD

**Issue by mikegrassotti** [DavyJonesLocker/capybara-email#18]
When testing a single page js app with capybara 2 it's finders are smart enough to wait for an element, up to `Capybara.default_wait_time`. This is important since the elements to be tested are often loaded asynchronously. 

The same is true for `open_email`. For example: Testing password reset form. User fills out a form, hits submit then we want to open email and verify contents. The submit triggers ajax, capybara test moves on and attempts to open email before it has been sent by the server:

```
fill_in 'Email', :with => 'guest@example.com'
click_on "Submit"
open_email('guest@example.com')
# FAIL!
```

As a workaround i have done the following:

```
click_on "Submit"
# Make sure we wait for this confirm before moving on with test!
page.should have_content 'A reset password email has been sent to you.'
open_email('guest@example.com')
```

I've not looked at capybara implementation but perhaps it is possible to applying the same strategy that is used there?

**Comment by YSavir** [comment]
Just had this happen... I really hate having to throw in a random `sleep` into my code along with a comment to qualify it. Would it be possible to add a `wait: <integer>` parameter to `open_email`, with wait defaulting to 0 seconds?

If that is viable, I would be happy to submit a PR.

**Comment by andrewhavens** [comment]
@YSavir I think the sleep should be built in. I think open_email will normally return immediately (so most people wouldn't see a delay), but in the times that an email could not be found, it should sleep for a short time, then try again up to a maximum of 3 seconds (or a configurable max wait time). Can you submit a PR for this? I would be happy to review and merge.

**Comment by YSavir** [comment]
@andrewhavens Sure thing! Will get one in this weekend.

**Comment by jezstephens** [comment]
> it should sleep for a short time, then try again up to a maximum of 3 seconds (or a configurable max wait time)

I think it would be intuitive for this to use `Capybara.default_max_wait_time`, rather than introducing a new config variable, so it works with `using_wait_time`.

**Comment by YSavir** [comment]
@jezstephens Yep, was planning on using that. This is, after all, *Capybara*-Email, and I'd rather keep true to it's name. :)
