### ISSUE TITLE
all_emails is great but difficult to find (documentation-wise)

### ISSUE THREAD

**Issue by jgillman** [DavyJonesLocker/capybara-email#59]
I'm testing some functionality that sends multiple emails on an action (order completion) and I was having a really hard time because I only knew about `current_email`.

Eventually I found myself reading through the specs for the gem and noticed `all_emails` which is perfect! It would be nice if it was mentioned in the readme :sweat_smile:

**Comment by obfuscoder** [comment]
You can create a PR to enhance the documentation with what you found out ;-)
