### ISSUE TITLE
Is this gem still active?

### ISSUE THREAD

**Issue by aguynamedben** [DavyJonesLocker/capybara-email#68]
Hi, this looks like a great gem, thanks for the work you put into it.

I wanted to make sure this gem is still being maintained before my team invests in integrating it. I noticed there hasn't been anything merged in about a year, the build status is "error", and the dependencies need updating.

* Are people still using this on production codebases?
* Are there any other alternatives (i.e. just getting Capybara to open a rendered email?)

FWIW I'm using Rails 5.1 with ActionMailer.

Thanks again.

**Comment by bcardarella** [comment]
I am no longer using Rails so it is not actively being developed. However I recognize that people use this gem and I am always open to bringing on active collaborators to maintain and push it forward.

**Comment by bensheldon** [comment]
I was added as a maintainer of the repository and am doing a bit of cleanup and ensuring that it works with the latest versions of Rails and RSpec.

> Are people still using this on production codebases?

I'm using this gem in my production codebase. It gets the job done of making it easy to assert emails within Integration/Feature/System tests.

> Are there any other alternatives (i.e. just getting Capybara to open a rendered email?)

There is [`email-spec`](https://github.com/email-spec/email-spec), though I don't believe it exposes capybara. It's rather simple to [create a capybara object from an html fragment](https://robots.thoughtbot.com/use-capybara-on-any-html-fragment-or-page). And it's rather simple to [retrieve the emails out of ActionMailer](https://stackoverflow.com/a/17223583).

...though at that point you've essentially built the functionality of this gem 😎: https://github.com/DavyJonesLocker/capybara-email/blob/master/lib/capybara/email/dsl.rb
