### ISSUE TITLE
Release current version on Rubygems

### ISSUE THREAD

**Issue by cseelus** [DavyJonesLocker/capybara-email#74]
Can you please release a new version? 2.5.0 was released February 17, 2016. Looks like there have been a few useful commits since then, especially regarding compatibility to Capybara 3.0.

**Comment by obfuscoder** [comment]
Yes, a release will be available shortly.

**Comment by cseelus** [comment]
Thanks for your efforts

**Comment by obfuscoder** [comment]
FYI, version capybara-email 3.0.0 has been released.
