### ISSUE TITLE
typo in doc

### ISSUE THREAD

**Issue by vishal-Pro** [DavyJonesLocker/capybara-email#80]
See this [here](https://github.com/DavyJonesLocker/capybara-email#setting-your-test-host)

```
# tests/test_helper.rb
ActionDispatch::IntegrationTest
  Capybara.server_port = 3001
  Capybara.app_host = 'http://localhost:3001'
end
```

end is unexpected !! please update

**Comment by obfuscoder** [comment]
Actually, a `do` was missing here.
