### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by shelmire** [DavyJonesLocker/capybara-email#81]
Hey @andrewhavens or whoever has the power, could you release a new version since there have been a few bugfixes since the last one and it's been a while?

**Comment by andrewhavens** [comment]
@shelmire Looks like I am not an admin on the gem at rubygems.org.

**Comment by bcardarella** [comment]
I am happy to. Do you both want in?

**Comment by andrewhavens** [comment]
You can add me. My RubyGems account email is email@andrewhavens.com

**Comment by bcardarella** [comment]
Let's see if I can remember my rubygems password 😛

**Comment by obfuscoder** [comment]
Sorry to answer so late. I would be able to build a release this weekend if that's ok.

**Comment by shelmire** [comment]
Awesome, thank you all for responding and for this gem!

**Comment by obfuscoder** [comment]
Version 3.0.2 has been released.
