### ISSUE TITLE
ERB code not being processed

### ISSUE THREAD

**Issue by bgvo** [DavyJonesLocker/capybara-email#83]
Sorry if this is by design, but not sure how to make erb code available.

## Version
3.0.2

## Test Case
I have a mailer view with variables that erb successfully processes in development.
When I'm on a test however, that view doesn't take into account any erb code, leaving empty the places where erb code must be rendered.

## Steps to reproduce
`some_mailer/first_email.html.erb`:
```erb
My first email.
Hi <%= @name %>
```
`test/integration/some_integration_test.rb`:
```ruby
test "@name is shown" do
  SomeMailer.first_email.deliver_now
  open_email("a@a.com")
  expect(current_email).to have_content 'my_name'
end
```

`app/mailers/some_mailer.rb`:
```ruby
class SomeMailer < ApplicationMailer
  def first_email
    @name = "my_name"
    mail(to: "a@a.com" subject: "my subject")
  end
end
```

## Expected Behavior
I expect the mail to have this content: ''my_name'

## Actual Behavior
ERB is not processed and hence 'my_name' is not present.

**Comment by obfuscoder** [comment]
This I use RSpec in my projects and I have working specs which render templates properly. My guess is that your project setup (test environment) is not correct. Your test code mixes RSpec and UnitTest syntax. Not sure if this might be the reason why your test fails. Can you please provide an example project on github which includes this failing test?

**Comment by bgvo** [comment]
Sorry, my error. I missed a silly conditional that stopped from executing the code. My apologies.

**Comment by obfuscoder** [comment]
Ok, no worries. I'll close this then.
